### ISSUE TITLE
If you scroll, it should trim any extra space on the window that is no longer being used

### ISSUE THREAD

**Issue by BrentFarris** [BrentFarris/TextGameMaker#20]
If you create a node and drag it off the screen (right or down), then the window expands to accommodate the required space. However, when you drag the node back towards the top left corner, the window stays at the same resized size. It should resize the window back down to only be as large as it needs to be.

Notice that currently, the scroll bars on the window dont shrink.

**Comment by pratik9818** [comment]
hi @BrentFarris i am going to work in this issue , please assign this issue to me

**Comment by BrentFarris** [comment]
> hi @BrentFarris i am going to work in this issue , please assign this issue to me

Sure thing! Let me know if you have any questions. I haven't exactly cleaned up the code and made use docs yet. I'll likely be starting that tonight

**Comment by BrentFarris** [comment]
Sorry ahead of time.

I'm closing this issue because I accidentally solved it trying to fix something else. There are a lot of other "good first issue" tasks in the project though if you're interested.
