### ISSUE TITLE
Remove HTTP and just use fetch api

### ISSUE THREAD

**Issue by BrentFarris** [BrentFarris/TextGameMaker#33]

**Comment by midikaif** [comment]
Hey @BrentFarris 
Do you want to replace HTTP to fetch in editor_application.js file?

**Comment by BrentFarris** [comment]
> Hey @BrentFarris Do you want to replace HTTP to fetch in editor_application.js file?

Hi @midikaif 

Yup, I'm basically looking to remove [HTTP.js](https://github.com/BrentFarris/TextGameMaker/blob/main/modules/engine/http.js), and the only usage is in [editor_application.js](https://github.com/BrentFarris/TextGameMaker/blob/main/modules/editor/editor_application.js#L275) I believe.

**Comment by MuhammadBabarWaseem** [comment]
can i do it?

**Comment by BrentFarris** [comment]
@MuhammadBabarWaseem 
> can i do it?

Thanks, I just merged in the change that @midikaif did, I've got a few other "good first issue" tasks if you're interested :)

**Comment by MuhammadBabarWaseem** [comment]
Yess let me know what are the other task
